#Steps Specific Configuration
general:
  changeManagement:
    endpoint: 'https://zsmswde0.eu.airbus.corp/sap/opu/odata/sap/AI_CRM_GW_CM_CI_SRV/'
    credentialsId: 'CM'
    type: 'SOLMAN'
steps:
  mtaBuild:
    buildTarget: 'NEO'
  transportRequestCreate:
    developmentSystemId: 'WEA~ABAP/801'
  transportRequestUploadFile:
    changeDocumentId: '46989',
    applicationId: 'HCP'
