#Steps Specific Configuration
general:
  changeManagement:
    endpoint: 'http://zsmvie0.eu.airbus.corp:8086/sap/opu/odata/sap/AI_CRM_GW_CM_CI_SRV/'
    credentialsId: 'CM'
    type: 'SOLMAN'
steps:
  mtaBuild:
    buildTarget: 'NEO'
  transportRequestCreate:
    developmentSystemId: 'WEA~ABAP/801'
  transportRequestUploadFile:
    applicationId: 'HCP'
    abapPackage: 'ZCOMMON'
    applicationDescription: 'Test devops'
    applicationId: 'Z_DEVOPS'
    applicationName: 'Z_DEVOPS'
