#Steps Specific Configuration
general:
  changeManagement:
    endpoint: 'https://zsmswde0.eu.airbus.corp//sap/opu/odata/sap/AI_CRM_GW_CM_CI_SRV/'
    credentialsId: 'CM'
    type: 'SOLMAN'
    clientOpts: '-Dorg.slf4j.simpleLogger.defaultLogLevel=trace -Dorg.apache.commons.logging.Log=org.apache.commons.logging.impl.SimpleLog -Dorg.apache.commons.logging.simplelog.showdatetime=true -Dorg.apache.commons.logging.simplelog.log.org.apache.http=DEBUG -Dorg.apache.commons.logging.simplelog.log.org.apache.http.wire=DEBUG'
    cmClientOpts: '-Djavax.net.ssl.trustStore=/var/jenkins_home/ssl/myTrustStore'
steps:
  mtaBuild:
    buildTarget: 'NEO'
  transportRequestCreate:
    developmentSystemId: 'WEA~ABAP/801'
  transportRequestUploadFile:
    abapPackage: 'ZCOMMON'
    applicationDescription: 'Test devops'
    applicationId: 'Z_DEVOPS'
    applicationName: 'Z_DEVOPS'
